test

diff --git a/stages/preflight/base.yaml b/stages/preflight/base.yaml
--- a/stages/preflight/base.yaml
+++ b/stages/preflight/base.yaml
@@ -1,3 +1,13 @@
+version validation:
+  stage: preprocess
+  cache: {}
+  script:
+    - |
+      if [ -z "$IMG_VERSION" ]; then
+        echo "Missing IMG_VERSION variable"
+        exit 1
+      fi
+
 preflight:
   stage: preflight
   allow_failure: true
