add dotenv artifact for version
Signed-off-by: James Petersen <jpetersenames@gmail.com>

diff --git a/stages/preflight/base.yaml b/stages/preflight/base.yaml
--- a/stages/preflight/base.yaml
+++ b/stages/preflight/base.yaml
@@ -1,7 +1,9 @@
 .preflight:
   stage: preflight
   image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/docker-git-bash-python:3.7
-  
+
+  dependencies:
+    - load scripts
 # TODO: Possibly check for deployment files?
 folder structure:
   extends: .preflight
@@ -26,3 +28,10 @@ build variables:
         echo "Missing IMG_VERSION variable in .gitlab-ci.yml file"
         exit 1
       fi
+    - |
+      if [ -z "$IMAGE_VERSION" ]; then
+        echo "Missing IMAGE_VERSION variable in environment"
+        exit 1
+      fi
+      echo "IMAGE_VERSION: ${IMAGE_VERSION}"
+
