format fix for script

diff --git a/stages/preflight/base.yaml b/stages/preflight/base.yaml
--- a/stages/preflight/base.yaml
+++ b/stages/preflight/base.yaml
@@ -35,9 +35,9 @@ build variables:
   allow_failure: true
   script:
     - |
-    if [ -z "$IMG_VERSION" ]; then
-      echo "Missing IMG_VERSION variable"
-      exit 1
-    fi
+      if [ -z "$IMG_VERSION" ]; then
+        echo "Missing IMG_VERSION variable"
+        exit 1
+      fi
 
   
