test

diff --git a/stages/preflight/base.yaml b/stages/preflight/base.yaml
--- a/stages/preflight/base.yaml
+++ b/stages/preflight/base.yaml
@@ -12,6 +12,11 @@ folder_structure:
     - ls -l README.md
     - ls -l Dockerfile
     - ls -l LICENSE
+    - |
+      if [ ls -l download.yaml ]; then
+        echo "download.yaml not found"
+        exit 1
+      fi
     - ls -l download.yaml
     - ls -l scripts
     - ls -l signatures
