arg

diff --git a/stages/preflight/base.yaml b/stages/preflight/base.yaml
--- a/stages/preflight/base.yaml
+++ b/stages/preflight/base.yaml
@@ -1,12 +1,12 @@
-version validation:
-  stage: preprocess
-  cache: {}
-  script:
-    - |
-      if [ -z "$IMG_VERSION" ]; then
-        echo "Missing IMG_VERSION variable"
-        exit 1
-      fi
+# version validation:
+#   stage: preprocess
+#   cache: {}
+#   script:
+#     - |
+#       if [ -z "$IMG_VERSION" ]; then
+#         echo "Missing IMG_VERSION variable"
+#         exit 1
+#       fi
 
 preflight:
   stage: preflight
