use ci_project_dir and scan location

diff --git a/stages/preflight/trufflehog.yaml b/stages/preflight/trufflehog.yaml
--- a/stages/preflight/trufflehog.yaml
+++ b/stages/preflight/trufflehog.yaml
@@ -6,16 +6,16 @@ trufflehog:
     entrypoint: [""]
   script:
     # Could add exceptions using --exclude_paths <exclusion file>
-    - git config http.postBuffer 524288000
-    - WARNINGS=$(trufflehog --json --regex --entropy False file://$(pwd))
-    - SUCCESS=$?
-    - |
-      if [ $SUCCESS -eq 0 ]; then
-        exit 0
-      fi
-    - 'echo "${WARNINGS}" | tee trufflehog.json'
-    - echo "FAILED Trufflehog scan. Exiting"
-    - exit "${SUCCESS}"
+    # - git config http.postBuffer 524288000
+    - 'trufflehog --regex --entropy False "file://${CI_PROJECT_DIR}"'
+    # - SUCCESS=$?
+    # - |
+    #   if [ $SUCCESS -eq 0 ]; then
+    #     exit 0
+    #   fi
+    # - 'echo "${WARNINGS}" | tee trufflehog.json'
+    # - echo "FAILED Trufflehog scan. Exiting"
+    # - exit "${SUCCESS}"
   artifacts:
     name: $CI_PROJECT_NAME-$CI_JOB_ID
     when: on_failure
