Project

diff --git a/stages/post-build/base.yaml b/stages/post-build/base.yaml
--- a/stages/post-build/base.yaml
+++ b/stages/post-build/base.yaml
@@ -136,20 +136,10 @@ tidelift-upload:
             -X POST "https://api.tidelift.com/external-api/v1/$TIDELIFT_ORG_NAME/groups?group_name=$TIDELIFT_PROJECT_GROUP")
             echo "$curl_output"
         }
-  
     - |
         response=$(make_request)
         echo "response -  $response"
-        response_error=$(cat $response | jq -r ".error")
-
-        echo "response_error - $response_error"
-
-        if (response_error == "existing_group") then
-            echo "Group already exist, $TIDELIFT_PROJECT_GROUP"
-        elif (response_error == "") then
-            echo "Created a new group, $TIDELIFT_PROJECT_GROUP"
-        fi
-
+ 
     #Tidelift will eventually need to process SPDX, JSON, XML SBOMs. 
     #For now we are focused on CycloneDX SBOMs file only
     #Notes: grep 'revision\|error' tidelift_alignment_log.json 
@@ -157,21 +147,19 @@ tidelift-upload:
     - echo "Tidelift Project New/Alignment Save"
     - echo "==================================="
 
-    - echo "Processing the SBOM with Tidelift CLI"
+    - echo "Processing the project Cyclonedx SBOM with Tidelift CLI"
     - ls | grep .json
 
-    - echo "Tidelift creating a new project $TIDELIFT_PROJECT_NAME in catalog $TIDELIFT_PROJECT_CATALOG with group $TIDELIFT_PROJECT_GROUP"
+    - echo "Process Project - $TIDELIFT_PROJECT_NAME in catalog $TIDELIFT_PROJECT_CATALOG with group $TIDELIFT_PROJECT_GROUP"
         
     - |
         ./tidelift projects new $TIDELIFT_PROJECT_NAME --organization $TIDELIFT_ORG_NAME --default-branch $TIDELIFT_PROJECT_BRANCH --catalog $TIDELIFT_PROJECT_CATALOG --group $TIDELIFT_PROJECT_GROUP --external-identifier $TIDELIFT_PROJECT_EXTERNAL_ID --force --json >> tl_cli_log.json
 
         cat tl_cli_log.json
-        TL_PRJ_ERROR=$(cat tl_cli_log.json | jq ".error")
-        cat TL_PRJ_ERROR
-        
-    - exit 1
+        TIDELIFT_ALIGNMENT_ERROR=$(cat tl_cli_log.json | jq -r ".error")
+        cat TIDELIFT_ALIGNMENT_ERROR
 
-    - echo "Tidelift projects new error value $TL_PRJ_ERROR"
+    - echo "Tidelift projects new error value $TIDELIFT_ALIGNMENT_ERROR"
 
     - | 
         if (TL_PRJ_NEW_ERROR == "") then 
@@ -180,8 +168,9 @@ tidelift-upload:
           echo "new project $TL_ALG_RESULT"
         fi
 
-        exit 1
+    - exit 1
 
+    - |
         if [ ["$TIDELIFT_ALIGNMENT_ID" != ""] && [$TIDELIFT_ALIGNMENT_ID =~ ^[0-9]+$] ] then
           echo "A new Iron Bank project is being processed by Tidelift: ${TIDELIFT_PROJECT_NAME} with External ID: ${TIDELIFT_PROJECT_EXTERNAL_ID}"
           echo "TIDELIFT_ALIGNMENT_ID: ${TIDELIFT_ALIGNMENT_ID}"
