Tidelift Group

diff --git a/stages/post-build/base.yaml b/stages/post-build/base.yaml
--- a/stages/post-build/base.yaml
+++ b/stages/post-build/base.yaml
@@ -76,6 +76,7 @@ tidelift-upload:
       - "${SBOM_DIR}/"
     expire_in: 1 week
   script:
+    #Tidelift integration with Iron Bank Pipeline for all projects, branches, and PRs. 
     - |
         echo "List of available SBOMs for project:"
         pushd ${SBOM_DIR}
@@ -84,6 +85,7 @@ tidelift-upload:
 
         echo "Coping Cyclonedx (sbom-cyclonedx-json.json) SBOM from Harbor artifacs directory"
         cp ${SBOM_DIR}/sbom-cyclonedx-json.json cyclonedx.json
+        echo "SBOM file copied to working directory"
 
         echo "Downloading Tidelift CLI binary file" 
         curl https://download.tidelift.com/cli/tidelift -o tidelift
@@ -96,15 +98,14 @@ tidelift-upload:
         echo "TIDELIFT_PROJECT_BRANCH= $TIDELIFT_PROJECT_BRANCH"
         echo "TIDELIFT_PROJECT_GROUP= $TIDELIFT_PROJECT_GROUP"
         
-        #env
-        #Environment Variable mapping to Tidelift project and catalog requirements fields
-        #Parse the IRONBANK_IMAGE_NAME AND IRONBANK_IMAGE TAG fields for Tidelift project and catalog 
-        #Tidelift Project Name: project-Name_tag-number_branch-name 
-        #External Prj Identifier: SupplierName/SubGroup/projectname/tagnumber/ 
-        #b=($(echo "$IRONBANK_IMAGE_TAG" | tr ':' '\n'))
-        #TIDELIFT_PROJECT_TAG=${b[1]}
-
-        echo "-- Parsing IRONBANK_IMAGE_NAME string values into Tidelift project variable values --"
+    #Environment Variable mapping to Tidelift project and catalog requirements fields
+    #Parse the IRONBANK_IMAGE_NAME AND IRONBANK_IMAGE tag fields for Tidelift project
+    #Tidelift Project Name: project-Name_tag-number_branch-name 
+    #External Prj Identifier: SupplierName/SubGroup/projectname/tagnumber/ 
+    #b=($(echo "$IRONBANK_IMAGE_TAG" | tr ':' '\n'))
+    #TIDELIFT_PROJECT_TAG=${b[1]}
+    - |
+        echo "Parsing IRONBANK_IMAGE_NAME values, assigning Tidelift project variable values:"
         a=($(echo "$IRONBANK_IMAGE_NAME" | tr '/' '\n'))
         TIDELIFT_PROJECT_SUPPLIER=${a[0]}
         TIDELIFT_PROJECT_SUPPLIER_TYPE=${a[1]}
@@ -118,23 +119,25 @@ tidelift-upload:
         echo "Project Tag: ${TIDELIFT_PROJECT_TAG}"
         echo "Project Name: ${TIDELIFT_PROJECT_NAME}"
         echo "Project External ID: ${TIDELIFT_PROJECT_EXTERNAL_ID}"
-        echo "-- Done --"
-        
-        echo "-* Starting Tidelift Project Alignment w/Container Image SBOM -*"
+    
     ###Tidelift Project Group Classification
-    #Create the Tidelift Project group based on Irin Bank Classification
-    - |
-      echo "-- Creating Tidelift Project Group --"
-      ./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME}
+    #Create the Tidelift Project group based on Iron Bank Classification
     #Notes: Create the new group, Success! Your group 'general' has been created with the slug 'project-group-name' will be shared 
-           #The best approach would be to create a catalog instead of checking for existing group names. Ignore - Error: that group already exists. 
-           #group_msg=$(./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME} | jq -r '.Error: that group already exists')
-    - echo "-* Processing the SBOM *-"
+    #       The best approach would be to create a catalog instead of checking for existing group names. Ignore - Error: that group already exists. 
+    #       group_msg=$(./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME} | jq -r '.Error: that group already exists')
     - |
-      echo "Coping Cyclonedx SBOM from artifacs directory"
-      cp ${SBOM_DIR}/sbom-cyclonedx-json.json cyclonedx.json
-    #cat cyclonedx.json
-    - echo "File copied"
+        echo "** Starting Tidelift Project Alignment w/Container Image SBOM **"
+        echo "Creating Tidelift Project Group: ${TIDELIFT_PROJECT_GROUP}"
+        
+        TL_GROUP_ERROR=(./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME})
+
+        echo "Group Error: $TL_GROUP_ERROR" 
+
+        echo "Processing the SBOM with Tidelift CLI"
+        ls | grep .json
+        
+        exit 1
+
     #Tidelift will eventually need to process SPDX, JSON, XML SBOMs. 
     #For now we are focused on CycloneDX SBOMs only
     #Delete# if ./tidelift projects new $TIDELIFT_PROJECT_NAME --organization $TIDELIFT_ORG_NAME --default-branch $TIDELIFT_PROJECT_BRANCH --catalog $TIDELIFT_PROJECT_SUPPLIER --group $TIDELIFT_PROJECT_GROUP --external-identifier $TIDELIFT_PROJECT_EXTERNAL_ID --force; then
@@ -145,10 +148,9 @@ tidelift-upload:
     # grep 'revision\|error' tidelift_alignment_log.json
 
     #./tidelift init $TIDELIFT_PROJECT_NAME --organization $TIDELIFT_ORG_NAME --catalog $TIDELIFT_PROJECT_CATALOG --default-branch $TIDELIFT_PROJECT_BRANCH --group $TIDELIFT_PROJECT_GROUP --external-identifier $TIDELIFT_PROJECT_EXTERNAL_ID --skip-dot-tidelift/--force --json --debug
-  
-    - echo "==========================="
-    - echo "Align project with Tidelift"
-    - echo "==========================="
+    - echo "==================================="
+    - echo "Tidelift Project New/Alignment Save"
+    - echo "==================================="
     - |
         echo "< Starting SBOM upload >"
 
