Error Handling

diff --git a/stages/post-build/base.yaml b/stages/post-build/base.yaml
--- a/stages/post-build/base.yaml
+++ b/stages/post-build/base.yaml
@@ -136,14 +136,20 @@ tidelift-upload:
             -X POST "https://api.tidelift.com/external-api/v1/$TIDELIFT_ORG_NAME/groups?group_name=$TIDELIFT_PROJECT_GROUP")
             echo "$curl_output"
         }
-    - response=$(make_request | jq ".error")
+    - response=$(make_request)
     - echo "response -  $response"
     - |
-        if (response == "existing_group") then
+        response_error = $(cat response | jq ".error")
+
+        echo "response_error - $response_error"
+        if [ response_error == "existing_group") ] then
             echo "Group already exist, $TIDELIFT_PROJECT_GROUP"
-        elif (response == "") then
+        elif (response_error == "") then
             echo "Created a new group, $TIDELIFT_PROJECT_GROUP"
         fi 
+
+    exit 1
+    
     #Tidelift will eventually need to process SPDX, JSON, XML SBOMs. 
     #For now we are focused on CycloneDX SBOMs file only
     #Notes: grep 'revision\|error' tidelift_alignment_log.json 
