Group JSON

diff --git a/stages/post-build/base.yaml b/stages/post-build/base.yaml
--- a/stages/post-build/base.yaml
+++ b/stages/post-build/base.yaml
@@ -129,8 +129,8 @@ tidelift-upload:
         echo "*** Starting Tidelift Project Alignment w/Container Image SBOM ***"
         echo "Creating Tidelift Project Group: ${TIDELIFT_PROJECT_GROUP}"
         
-    #TL_GROUP_ERROR=$(./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME})
-    #echo "Group Error: $TL_GROUP_ERROR" 
+        TL_GROUP_ERROR=$(./tidelift groups new ${TIDELIFT_PROJECT_GROUP} --organization ${TIDELIFT_ORG_NAME} --json)
+        echo "Group Error: $TL_GROUP_ERROR" 
 
     #Tidelift will eventually need to process SPDX, JSON, XML SBOMs. 
     #For now we are focused on CycloneDX SBOMs file only
@@ -145,7 +145,13 @@ tidelift-upload:
 
         echo "Tidelift creating a new project $TIDELIFT_PROJECT_NAME in catalog $TIDELIFT_PROJECT_CATALOG with group $TIDELIFT_PROJECT_GROUP"
         
-        TL_PRJ_NEW_ERROR=$(./tidelift projects new $TIDELIFT_PROJECT_NAME --organization $TIDELIFT_ORG_NAME --default-branch $TIDELIFT_PROJECT_BRANCH --catalog $TIDELIFT_PROJECT_CATALOG --group $TIDELIFT_PROJECT_GROUP --external-identifier $TIDELIFT_PROJECT_EXTERNAL_ID --force --json | jq -r ".error") 
+        ./tidelift projects new $TIDELIFT_PROJECT_NAME --organization $TIDELIFT_ORG_NAME --default-branch $TIDELIFT_PROJECT_BRANCH --catalog $TIDELIFT_PROJECT_CATALOG --group $TIDELIFT_PROJECT_GROUP --external-identifier $TIDELIFT_PROJECT_EXTERNAL_ID --force --json >> tl_cli_log.json
+
+        cat tl_cli_log.json
+        TL_PRJ_ERROR=$(cat tl_cli_log.json | jq ".error")
+        cat TL_PRJ_ERROR
+
+        exit 1
         
         echo "Tidelift projects new error value: $TL_PRJ_ERROR"
 
@@ -156,7 +162,7 @@ tidelift-upload:
         fi
 
         exit 1
-        
+
         if [ ["$TIDELIFT_ALIGNMENT_ID" != ""] && [$TIDELIFT_ALIGNMENT_ID =~ ^[0-9]+$] ] then
           echo "A new Iron Bank project is being processed by Tidelift: ${TIDELIFT_PROJECT_NAME} with External ID: ${TIDELIFT_PROJECT_EXTERNAL_ID}"
           echo "TIDELIFT_ALIGNMENT_ID: ${TIDELIFT_ALIGNMENT_ID}"
