remove inspect for base_image_type from sh

diff --git a/stages/scanning/openscap-compliance.yaml b/stages/scanning/openscap-compliance.yaml
--- a/stages/scanning/openscap-compliance.yaml
+++ b/stages/scanning/openscap-compliance.yaml
@@ -26,6 +26,26 @@ openscap compliance ubuntu:
   extends: .scanning
   stage: scanning
   image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/ubupodscap1804:1.3.2
+  before_script:
+  - DOCKER_IMAGE_PATH=$(podman load -i "${ARTIFACT_STORAGE}"/build/"${CI_PROJECT_NAME}"-"${CI_PIPELINE_ID}".tar | awk '{print $3}')
+  - export ${DOCKER_IMAGE_PATH}
+  - base_image_type=$(podman inspect -f '{{index .Labels "com.redhat.component"}}' "${DOCKER_IMAGE_PATH}")
+  - |
+    if [[ "${base_image_type}" == "" ]]; then
+      base_image_type=$(podman inspect -f '{{index .Labels "os_type"}}' "${DOCKER_IMAGE_PATH}")
+      if [[ "${base_image_type}" == "" ]]; then
+        base_image_type=$(podman inspect -f '{{index .Labels "mil.dso.ironbank.os-type"}}' "${DOCKER_IMAGE_PATH}")
+        if [[ "${base_image_type}" == "" ]]; then
+          labels=$(podman inspect -f '{{index .Labels}}' "${DOCKER_IMAGE_PATH}")
+          echo "Unknown image type. Can't choose security guide. labels: ${labels}"
+          exit 1
+        fi
+      fi
+    fi
+  - export ${base_image_type}
+  rules:
+    if: '$(echo ${base_image_type} | cut -d- -f1 | sed 's/[0-9]//g') != "ubuntu'
+    when: never
   except:
     variables:
       - $DISTROLESS
